version: "3.3"

# networks:
#   default:
#     driver: bridge

services:
  ## shared/managed services

  ## application services

  bancho-service:
    image: bancho-service:latest
    ports:
      - 11000:80
    environment:
      # asgi + app
      - APP_ENV=local
      - APP_COMPONENT=api
      - APP_HOST=0.0.0.0
      - APP_PORT=80
      - LOG_LEVEL=20
    volumes:
      - ./mount:/srv/root
      - ./scripts:/scripts
    # depends_on:
